name: Push Docker Image to ECR
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: ${{ github.sha }}
         ECR_REPOSITORY: node_repo
      - name: Build and push Docker image
    registry: $537611828196.dkr.ecr.$us-east-1.amazonaws.com
              aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 537611828196.dkr.ecr.us-east-1.amazonaws.com
      - name: Build and push Docker image
         run: |
             docker build -t node_repo .
             docker tag node_repo:latest 537611828196.dkr.ecr.us-east-1.amazonaws.com/node_repo:latest
             docker push 537611828196.dkr.ecr.us-east-1.amazonaws.com/node_repo:latest

             
             